import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { FontIcon } from '../models/interfaces/font-icon.interace';

/**
 * Service provide information about available font icons.
 */
@Injectable()
export class FontIconService {

  private fontIconClasses: Array<FontIcon> = [
    {css: 'fa-500px', label: '500px'},
    {css: 'fa-adjust', label: 'Adjust'},
    {css: 'fa-adn', label: 'Adn'},
    {css: 'fa-align-center', label: 'Align center'},
    {css: 'fa-align-justify', label: 'Align justify'},
    {css: 'fa-align-left', label: 'Align left'},
    {css: 'fa-align-right', label: 'Align right'},
    {css: 'fa-amazon', label: 'Amazon'},
    {css: 'fa-ambulance', label: 'Ambulance'},
    {css: 'fa-anchor', label: 'Anchor'},
    {css: 'fa-android', label: 'Android'},
    {css: 'fa-angellist', label: 'Angellist'},
    {css: 'fa-angle-double-down', label: 'Angle double down'},
    {css: 'fa-angle-double-left', label: 'Angle double left'},
    {css: 'fa-angle-double-right', label: 'Angle double right'},
    {css: 'fa-angle-double-up', label: 'Angle double up'},
    {css: 'fa-angle-down', label: 'Angle down'},
    {css: 'fa-angle-left', label: 'Angle left'},
    {css: 'fa-angle-right', label: 'Angle right'},
    {css: 'fa-angle-up', label: 'Angle up'},
    {css: 'fa-apple', label: 'Apple'},
    {css: 'fa-archive', label: 'Archive'},
    {css: 'fa-area-chart', label: 'Area chart'},
    {css: 'fa-arrow-circle-down', label: 'Arrow circle down'},
    {css: 'fa-arrow-circle-left', label: 'Arrow circle left'},
    {css: 'fa-arrow-circle-o-down', label: 'Arrow circle o down'},
    {css: 'fa-arrow-circle-o-left', label: 'Arrow circle o left'},
    {css: 'fa-arrow-circle-o-right', label: 'Arrow circle o right'},
    {css: 'fa-arrow-circle-o-up', label: 'Arrow circle o up'},
    {css: 'fa-arrow-circle-right', label: 'Arrow circle right'},
    {css: 'fa-arrow-circle-up', label: 'Arrow circle up'},
    {css: 'fa-arrow-down', label: 'Arrow down'},
    {css: 'fa-arrow-left', label: 'Arrow left'},
    {css: 'fa-arrow-right', label: 'Arrow right'},
    {css: 'fa-arrow-up', label: 'Arrow up'},
    {css: 'fa-arrows', label: 'Arrows'},
    {css: 'fa-arrows-alt', label: 'Arrows alt'},
    {css: 'fa-arrows-h', label: 'Arrows h'},
    {css: 'fa-arrows-v', label: 'Arrows v'},
    {css: 'fa-asterisk', label: 'Asterisk'},
    {css: 'fa-at', label: 'At'},
    {css: 'fa-backward', label: 'Backward'},
    {css: 'fa-balance-scale', label: 'Balance scale'},
    {css: 'fa-ban', label: 'Ban'},
    {css: 'fa-bar-chart', label: 'Bar chart'},
    {css: 'fa-barcode', label: 'Barcode'},
    {css: 'fa-bars', label: 'Bars'},
    {css: 'fa-battery-empty', label: 'Battery empty'},
    {css: 'fa-battery-full', label: 'Battery full'},
    {css: 'fa-battery-half', label: 'Battery half'},
    {css: 'fa-battery-quarter', label: 'Battery quarter'},
    {css: 'fa-battery-three-quarters', label: 'Battery three quarters'},
    {css: 'fa-bed', label: 'Bed'},
    {css: 'fa-beer', label: 'Beer'},
    {css: 'fa-behance', label: 'Behance'},
    {css: 'fa-behance-square', label: 'Behance square'},
    {css: 'fa-bell', label: 'Bell'},
    {css: 'fa-bell-o', label: 'Bell o'},
    {css: 'fa-bell-slash', label: 'Bell slash'},
    {css: 'fa-bell-slash-o', label: 'Bell slash o'},
    {css: 'fa-bicycle', label: 'Bicycle'},
    {css: 'fa-binoculars', label: 'Binoculars'},
    {css: 'fa-birthday-cake', label: 'Birthday cake'},
    {css: 'fa-bitbucket', label: 'Bitbucket'},
    {css: 'fa-bitbucket-square', label: 'Bitbucket square'},
    {css: 'fa-black-tie', label: 'Black tie'},
    {css: 'fa-bold', label: 'Bold'},
    {css: 'fa-bolt', label: 'Bolt'},
    {css: 'fa-bomb', label: 'Bomb'},
    {css: 'fa-book', label: 'Book'},
    {css: 'fa-bookmark', label: 'Bookmark'},
    {css: 'fa-bookmark-o', label: 'Bookmark o'},
    {css: 'fa-briefcase', label: 'Briefcase'},
    {css: 'fa-btc', label: 'Btc'},
    {css: 'fa-bug', label: 'Bug'},
    {css: 'fa-building', label: 'Building'},
    {css: 'fa-building-o', label: 'Building o'},
    {css: 'fa-bullhorn', label: 'Bullhorn'},
    {css: 'fa-bullseye', label: 'Bullseye'},
    {css: 'fa-bus', label: 'Bus'},
    {css: 'fa-buysellads', label: 'Buysellads'},
    {css: 'fa-calculator', label: 'Calculator'},
    {css: 'fa-calendar', label: 'Calendar'},
    {css: 'fa-calendar-check-o', label: 'Calendar check o'},
    {css: 'fa-calendar-minus-o', label: 'Calendar minus o'},
    {css: 'fa-calendar-o', label: 'Calendar o'},
    {css: 'fa-calendar-plus-o', label: 'Calendar plus o'},
    {css: 'fa-calendar-times-o', label: 'Calendar times o'},
    {css: 'fa-camera', label: 'Camera'},
    {css: 'fa-camera-retro', label: 'Camera retro'},
    {css: 'fa-car', label: 'Car'},
    {css: 'fa-caret-down', label: 'Caret down'},
    {css: 'fa-caret-left', label: 'Caret left'},
    {css: 'fa-caret-right', label: 'Caret right'},
    {css: 'fa-caret-square-o-down', label: 'Caret square o down'},
    {css: 'fa-caret-square-o-left', label: 'Caret square o left'},
    {css: 'fa-caret-square-o-right', label: 'Caret square o right'},
    {css: 'fa-caret-square-o-up', label: 'Caret square o up'},
    {css: 'fa-caret-up', label: 'Caret up'},
    {css: 'fa-cart-arrow-down', label: 'Cart arrow down'},
    {css: 'fa-cart-plus', label: 'Cart plus'},
    {css: 'fa-cc', label: 'Cc'},
    {css: 'fa-cc-amex', label: 'Cc amex'},
    {css: 'fa-cc-diners-club', label: 'Cc diners club'},
    {css: 'fa-cc-discover', label: 'Cc discover'},
    {css: 'fa-cc-jcb', label: 'Cc jcb'},
    {css: 'fa-cc-mastercard', label: 'Cc mastercard'},
    {css: 'fa-cc-paypal', label: 'Cc paypal'},
    {css: 'fa-cc-stripe', label: 'Cc stripe'},
    {css: 'fa-cc-visa', label: 'Cc visa'},
    {css: 'fa-certificate', label: 'Certificate'},
    {css: 'fa-chain-broken', label: 'Chain broken'},
    {css: 'fa-check', label: 'Check'},
    {css: 'fa-check-circle', label: 'Check circle'},
    {css: 'fa-check-circle-o', label: 'Check circle o'},
    {css: 'fa-check-square', label: 'Check square'},
    {css: 'fa-check-square-o', label: 'Check square o'},
    {css: 'fa-chevron-circle-down', label: 'Chevron circle down'},
    {css: 'fa-chevron-circle-left', label: 'Chevron circle left'},
    {css: 'fa-chevron-circle-right', label: 'Chevron circle right'},
    {css: 'fa-chevron-circle-up', label: 'Chevron circle up'},
    {css: 'fa-chevron-down', label: 'Chevron down'},
    {css: 'fa-chevron-left', label: 'Chevron left'},
    {css: 'fa-chevron-right', label: 'Chevron right'},
    {css: 'fa-chevron-up', label: 'Chevron up'},
    {css: 'fa-child', label: 'Child'},
    {css: 'fa-chrome', label: 'Chrome'},
    {css: 'fa-circle', label: 'Circle'},
    {css: 'fa-circle-o', label: 'Circle o'},
    {css: 'fa-circle-o-notch', label: 'Circle o notch'},
    {css: 'fa-circle-thin', label: 'Circle thin'},
    {css: 'fa-clipboard', label: 'Clipboard'},
    {css: 'fa-clock-o', label: 'Clock o'},
    {css: 'fa-clone', label: 'Clone'},
    {css: 'fa-cloud', label: 'Cloud'},
    {css: 'fa-cloud-download', label: 'Cloud download'},
    {css: 'fa-cloud-upload', label: 'Cloud upload'},
    {css: 'fa-code', label: 'Code'},
    {css: 'fa-code-fork', label: 'Code fork'},
    {css: 'fa-codepen', label: 'Codepen'},
    {css: 'fa-coffee', label: 'Coffee'},
    {css: 'fa-cog', label: 'Cog'},
    {css: 'fa-cogs', label: 'Cogs'},
    {css: 'fa-columns', label: 'Columns'},
    {css: 'fa-comment', label: 'Comment'},
    {css: 'fa-comment-o', label: 'Comment o'},
    {css: 'fa-commenting', label: 'Commenting'},
    {css: 'fa-commenting-o', label: 'Commenting o'},
    {css: 'fa-comments', label: 'Comments'},
    {css: 'fa-comments-o', label: 'Comments o'},
    {css: 'fa-compass', label: 'Compass'},
    {css: 'fa-compress', label: 'Compress'},
    {css: 'fa-connectdevelop', label: 'Connectdevelop'},
    {css: 'fa-contao', label: 'Contao'},
    {css: 'fa-copyright', label: 'Copyright'},
    {css: 'fa-creative-commons', label: 'Creative commons'},
    {css: 'fa-credit-card', label: 'Credit card'},
    {css: 'fa-crop', label: 'Crop'},
    {css: 'fa-crosshairs', label: 'Crosshairs'},
    {css: 'fa-css3', label: 'Css3'},
    {css: 'fa-cube', label: 'Cube'},
    {css: 'fa-cubes', label: 'Cubes'},
    {css: 'fa-cutlery', label: 'Cutlery'},
    {css: 'fa-dashcube', label: 'Dashcube'},
    {css: 'fa-database', label: 'Database'},
    {css: 'fa-delicious', label: 'Delicious'},
    {css: 'fa-desktop', label: 'Desktop'},
    {css: 'fa-deviantart', label: 'Deviantart'},
    {css: 'fa-diamond', label: 'Diamond'},
    {css: 'fa-digg', label: 'Digg'},
    {css: 'fa-dot-circle-o', label: 'Dot circle o'},
    {css: 'fa-download', label: 'Download'},
    {css: 'fa-dribbble', label: 'Dribbble'},
    {css: 'fa-dropbox', label: 'Dropbox'},
    {css: 'fa-drupal', label: 'Drupal'},
    {css: 'fa-eject', label: 'Eject'},
    {css: 'fa-ellipsis-h', label: 'Ellipsis h'},
    {css: 'fa-ellipsis-v', label: 'Ellipsis v'},
    {css: 'fa-empire', label: 'Empire'},
    {css: 'fa-envelope', label: 'Envelope'},
    {css: 'fa-envelope-o', label: 'Envelope o'},
    {css: 'fa-envelope-square', label: 'Envelope square'},
    {css: 'fa-eraser', label: 'Eraser'},
    {css: 'fa-eur', label: 'Eur'},
    {css: 'fa-exchange', label: 'Exchange'},
    {css: 'fa-exclamation', label: 'Exclamation'},
    {css: 'fa-exclamation-circle', label: 'Exclamation circle'},
    {css: 'fa-exclamation-triangle', label: 'Exclamation triangle'},
    {css: 'fa-expand', label: 'Expand'},
    {css: 'fa-expeditedssl', label: 'Expeditedssl'},
    {css: 'fa-external-link', label: 'External link'},
    {css: 'fa-external-link-square', label: 'External link square'},
    {css: 'fa-eye', label: 'Eye'},
    {css: 'fa-eye-slash', label: 'Eye slash'},
    {css: 'fa-eyedropper', label: 'Eyedropper'},
    {css: 'fa-facebook', label: 'Facebook'},
    {css: 'fa-facebook-official', label: 'Facebook official'},
    {css: 'fa-facebook-square', label: 'Facebook square'},
    {css: 'fa-fast-backward', label: 'Fast backward'},
    {css: 'fa-fast-forward', label: 'Fast forward'},
    {css: 'fa-fax', label: 'Fax'},
    {css: 'fa-female', label: 'Female'},
    {css: 'fa-fighter-jet', label: 'Fighter jet'},
    {css: 'fa-file', label: 'File'},
    {css: 'fa-file-archive-o', label: 'File archive o'},
    {css: 'fa-file-audio-o', label: 'File audio o'},
    {css: 'fa-file-code-o', label: 'File code o'},
    {css: 'fa-file-excel-o', label: 'File excel o'},
    {css: 'fa-file-image-o', label: 'File image o'},
    {css: 'fa-file-o', label: 'File o'},
    {css: 'fa-file-pdf-o', label: 'File pdf o'},
    {css: 'fa-file-powerpoint-o', label: 'File powerpoint o'},
    {css: 'fa-file-text', label: 'File text'},
    {css: 'fa-file-text-o', label: 'File text o'},
    {css: 'fa-file-video-o', label: 'File video o'},
    {css: 'fa-file-word-o', label: 'File word o'},
    {css: 'fa-files-o', label: 'Files o'},
    {css: 'fa-film', label: 'Film'},
    {css: 'fa-filter', label: 'Filter'},
    {css: 'fa-fire', label: 'Fire'},
    {css: 'fa-fire-extinguisher', label: 'Fire extinguisher'},
    {css: 'fa-firefox', label: 'Firefox'},
    {css: 'fa-flag', label: 'Flag'},
    {css: 'fa-flag-checkered', label: 'Flag checkered'},
    {css: 'fa-flag-o', label: 'Flag o'},
    {css: 'fa-flask', label: 'Flask'},
    {css: 'fa-flickr', label: 'Flickr'},
    {css: 'fa-floppy-o', label: 'Floppy o'},
    {css: 'fa-folder', label: 'Folder'},
    {css: 'fa-folder-o', label: 'Folder o'},
    {css: 'fa-folder-open', label: 'Folder open'},
    {css: 'fa-folder-open-o', label: 'Folder open o'},
    {css: 'fa-font', label: 'Font'},
    {css: 'fa-fonticons', label: 'Fonticons'},
    {css: 'fa-forumbee', label: 'Forumbee'},
    {css: 'fa-forward', label: 'Forward'},
    {css: 'fa-foursquare', label: 'Foursquare'},
    {css: 'fa-frown-o', label: 'Frown o'},
    {css: 'fa-futbol-o', label: 'Futbol o'},
    {css: 'fa-gamepad', label: 'Gamepad'},
    {css: 'fa-gavel', label: 'Gavel'},
    {css: 'fa-gbp', label: 'Gbp'},
    {css: 'fa-genderless', label: 'Genderless'},
    {css: 'fa-get-pocket', label: 'Get pocket'},
    {css: 'fa-gg', label: 'Gg'},
    {css: 'fa-gg-circle', label: 'Gg circle'},
    {css: 'fa-gift', label: 'Gift'},
    {css: 'fa-git', label: 'Git'},
    {css: 'fa-git-square', label: 'Git square'},
    {css: 'fa-github', label: 'Github'},
    {css: 'fa-github-alt', label: 'Github alt'},
    {css: 'fa-github-square', label: 'Github square'},
    {css: 'fa-glass', label: 'Glass'},
    {css: 'fa-globe', label: 'Globe'},
    {css: 'fa-google', label: 'Google'},
    {css: 'fa-google-plus', label: 'Google plus'},
    {css: 'fa-google-plus-square', label: 'Google plus square'},
    {css: 'fa-google-wallet', label: 'Google wallet'},
    {css: 'fa-graduation-cap', label: 'Graduation cap'},
    {css: 'fa-gratipay', label: 'Gratipay'},
    {css: 'fa-h-square', label: 'H square'},
    {css: 'fa-hacker-news', label: 'Hacker news'},
    {css: 'fa-hand-lizard-o', label: 'Hand lizard o'},
    {css: 'fa-hand-o-down', label: 'Hand o down'},
    {css: 'fa-hand-o-left', label: 'Hand o left'},
    {css: 'fa-hand-o-right', label: 'Hand o right'},
    {css: 'fa-hand-o-up', label: 'Hand o up'},
    {css: 'fa-hand-paper-o', label: 'Hand paper o'},
    {css: 'fa-hand-peace-o', label: 'Hand peace o'},
    {css: 'fa-hand-pointer-o', label: 'Hand pointer o'},
    {css: 'fa-hand-rock-o', label: 'Hand rock o'},
    {css: 'fa-hand-scissors-o', label: 'Hand scissors o'},
    {css: 'fa-hand-spock-o', label: 'Hand spock o'},
    {css: 'fa-hdd-o', label: 'Hdd o'},
    {css: 'fa-header', label: 'Header'},
    {css: 'fa-headphones', label: 'Headphones'},
    {css: 'fa-heart', label: 'Heart'},
    {css: 'fa-heart-o', label: 'Heart o'},
    {css: 'fa-heartbeat', label: 'Heartbeat'},
    {css: 'fa-history', label: 'History'},
    {css: 'fa-home', label: 'Home'},
    {css: 'fa-hospital-o', label: 'Hospital o'},
    {css: 'fa-hourglass', label: 'Hourglass'},
    {css: 'fa-hourglass-end', label: 'Hourglass end'},
    {css: 'fa-hourglass-half', label: 'Hourglass half'},
    {css: 'fa-hourglass-o', label: 'Hourglass o'},
    {css: 'fa-hourglass-start', label: 'Hourglass start'},
    {css: 'fa-houzz', label: 'Houzz'},
    {css: 'fa-html5', label: 'Html5'},
    {css: 'fa-i-cursor', label: 'I cursor'},
    {css: 'fa-ils', label: 'Ils'},
    {css: 'fa-inbox', label: 'Inbox'},
    {css: 'fa-indent', label: 'Indent'},
    {css: 'fa-industry', label: 'Industry'},
    {css: 'fa-info', label: 'Info'},
    {css: 'fa-info-circle', label: 'Info circle'},
    {css: 'fa-inr', label: 'Inr'},
    {css: 'fa-instagram', label: 'Instagram'},
    {css: 'fa-internet-explorer', label: 'Internet explorer'},
    {css: 'fa-ioxhost', label: 'Ioxhost'},
    {css: 'fa-italic', label: 'Italic'},
    {css: 'fa-joomla', label: 'Joomla'},
    {css: 'fa-jpy', label: 'Jpy'},
    {css: 'fa-jsfiddle', label: 'Jsfiddle'},
    {css: 'fa-key', label: 'Key'},
    {css: 'fa-keyboard-o', label: 'Keyboard o'},
    {css: 'fa-krw', label: 'Krw'},
    {css: 'fa-language', label: 'Language'},
    {css: 'fa-laptop', label: 'Laptop'},
    {css: 'fa-lastfm', label: 'Lastfm'},
    {css: 'fa-lastfm-square', label: 'Lastfm square'},
    {css: 'fa-leaf', label: 'Leaf'},
    {css: 'fa-leanpub', label: 'Leanpub'},
    {css: 'fa-lemon-o', label: 'Lemon o'},
    {css: 'fa-level-down', label: 'Level down'},
    {css: 'fa-level-up', label: 'Level up'},
    {css: 'fa-life-ring', label: 'Life ring'},
    {css: 'fa-lightbulb-o', label: 'Lightbulb o'},
    {css: 'fa-line-chart', label: 'Line chart'},
    {css: 'fa-link', label: 'Link'},
    {css: 'fa-linkedin', label: 'Linkedin'},
    {css: 'fa-linkedin-square', label: 'Linkedin square'},
    {css: 'fa-linux', label: 'Linux'},
    {css: 'fa-list', label: 'List'},
    {css: 'fa-list-alt', label: 'List alt'},
    {css: 'fa-list-ol', label: 'List ol'},
    {css: 'fa-list-ul', label: 'List ul'},
    {css: 'fa-location-arrow', label: 'Location arrow'},
    {css: 'fa-lock', label: 'Lock'},
    {css: 'fa-long-arrow-down', label: 'Long arrow down'},
    {css: 'fa-long-arrow-left', label: 'Long arrow left'},
    {css: 'fa-long-arrow-right', label: 'Long arrow right'},
    {css: 'fa-long-arrow-up', label: 'Long arrow up'},
    {css: 'fa-magic', label: 'Magic'},
    {css: 'fa-magnet', label: 'Magnet'},
    {css: 'fa-male', label: 'Male'},
    {css: 'fa-map', label: 'Map'},
    {css: 'fa-map-marker', label: 'Map marker'},
    {css: 'fa-map-o', label: 'Map o'},
    {css: 'fa-map-pin', label: 'Map pin'},
    {css: 'fa-map-signs', label: 'Map signs'},
    {css: 'fa-mars', label: 'Mars'},
    {css: 'fa-mars-double', label: 'Mars double'},
    {css: 'fa-mars-stroke', label: 'Mars stroke'},
    {css: 'fa-mars-stroke-h', label: 'Mars stroke h'},
    {css: 'fa-mars-stroke-v', label: 'Mars stroke v'},
    {css: 'fa-maxcdn', label: 'Maxcdn'},
    {css: 'fa-meanpath', label: 'Meanpath'},
    {css: 'fa-medium', label: 'Medium'},
    {css: 'fa-medkit', label: 'Medkit'},
    {css: 'fa-meh-o', label: 'Meh o'},
    {css: 'fa-mercury', label: 'Mercury'},
    {css: 'fa-microphone', label: 'Microphone'},
    {css: 'fa-microphone-slash', label: 'Microphone slash'},
    {css: 'fa-minus', label: 'Minus'},
    {css: 'fa-minus-circle', label: 'Minus circle'},
    {css: 'fa-minus-square', label: 'Minus square'},
    {css: 'fa-minus-square-o', label: 'Minus square o'},
    {css: 'fa-mobile', label: 'Mobile'},
    {css: 'fa-money', label: 'Money'},
    {css: 'fa-moon-o', label: 'Moon o'},
    {css: 'fa-motorcycle', label: 'Motorcycle'},
    {css: 'fa-mouse-pointer', label: 'Mouse pointer'},
    {css: 'fa-music', label: 'Music'},
    {css: 'fa-neuter', label: 'Neuter'},
    {css: 'fa-newspaper-o', label: 'Newspaper o'},
    {css: 'fa-object-group', label: 'Object group'},
    {css: 'fa-object-ungroup', label: 'Object ungroup'},
    {css: 'fa-odnoklassniki', label: 'Odnoklassniki'},
    {css: 'fa-odnoklassniki-square', label: 'Odnoklassniki square'},
    {css: 'fa-opencart', label: 'Opencart'},
    {css: 'fa-openid', label: 'Openid'},
    {css: 'fa-opera', label: 'Opera'},
    {css: 'fa-optin-monster', label: 'Optin monster'},
    {css: 'fa-outdent', label: 'Outdent'},
    {css: 'fa-pagelines', label: 'Pagelines'},
    {css: 'fa-paint-brush', label: 'Paint brush'},
    {css: 'fa-paper-plane', label: 'Paper plane'},
    {css: 'fa-paper-plane-o', label: 'Paper plane o'},
    {css: 'fa-paperclip', label: 'Paperclip'},
    {css: 'fa-paragraph', label: 'Paragraph'},
    {css: 'fa-pause', label: 'Pause'},
    {css: 'fa-paw', label: 'Paw'},
    {css: 'fa-paypal', label: 'Paypal'},
    {css: 'fa-pencil', label: 'Pencil'},
    {css: 'fa-pencil-square', label: 'Pencil square'},
    {css: 'fa-pencil-square-o', label: 'Pencil square o'},
    {css: 'fa-phone', label: 'Phone'},
    {css: 'fa-phone-square', label: 'Phone square'},
    {css: 'fa-picture-o', label: 'Picture o'},
    {css: 'fa-pie-chart', label: 'Pie chart'},
    {css: 'fa-pied-piper', label: 'Pied piper'},
    {css: 'fa-pied-piper-alt', label: 'Pied piper alt'},
    {css: 'fa-pinterest', label: 'Pinterest'},
    {css: 'fa-pinterest-p', label: 'Pinterest p'},
    {css: 'fa-pinterest-square', label: 'Pinterest square'},
    {css: 'fa-plane', label: 'Plane'},
    {css: 'fa-play', label: 'Play'},
    {css: 'fa-play-circle', label: 'Play circle'},
    {css: 'fa-play-circle-o', label: 'Play circle o'},
    {css: 'fa-plug', label: 'Plug'},
    {css: 'fa-plus', label: 'Plus'},
    {css: 'fa-plus-circle', label: 'Plus circle'},
    {css: 'fa-plus-square', label: 'Plus square'},
    {css: 'fa-plus-square-o', label: 'Plus square o'},
    {css: 'fa-power-off', label: 'Power off'},
    {css: 'fa-print', label: 'Print'},
    {css: 'fa-puzzle-piece', label: 'Puzzle piece'},
    {css: 'fa-qq', label: 'Qq'},
    {css: 'fa-qrcode', label: 'Qrcode'},
    {css: 'fa-question', label: 'Question'},
    {css: 'fa-question-circle', label: 'Question circle'},
    {css: 'fa-quote-left', label: 'Quote left'},
    {css: 'fa-quote-right', label: 'Quote right'},
    {css: 'fa-random', label: 'Random'},
    {css: 'fa-rebel', label: 'Rebel'},
    {css: 'fa-recycle', label: 'Recycle'},
    {css: 'fa-reddit', label: 'Reddit'},
    {css: 'fa-reddit-square', label: 'Reddit square'},
    {css: 'fa-refresh', label: 'Refresh'},
    {css: 'fa-registered', label: 'Registered'},
    {css: 'fa-renren', label: 'Renren'},
    {css: 'fa-repeat', label: 'Repeat'},
    {css: 'fa-reply', label: 'Reply'},
    {css: 'fa-reply-all', label: 'Reply all'},
    {css: 'fa-retweet', label: 'Retweet'},
    {css: 'fa-road', label: 'Road'},
    {css: 'fa-rocket', label: 'Rocket'},
    {css: 'fa-rss', label: 'Rss'},
    {css: 'fa-rss-square', label: 'Rss square'},
    {css: 'fa-rub', label: 'Rub'},
    {css: 'fa-safari', label: 'Safari'},
    {css: 'fa-scissors', label: 'Scissors'},
    {css: 'fa-search', label: 'Search'},
    {css: 'fa-search-minus', label: 'Search minus'},
    {css: 'fa-search-plus', label: 'Search plus'},
    {css: 'fa-sellsy', label: 'Sellsy'},
    {css: 'fa-server', label: 'Server'},
    {css: 'fa-share', label: 'Share'},
    {css: 'fa-share-alt', label: 'Share alt'},
    {css: 'fa-share-alt-square', label: 'Share alt square'},
    {css: 'fa-share-square', label: 'Share square'},
    {css: 'fa-share-square-o', label: 'Share square o'},
    {css: 'fa-shield', label: 'Shield'},
    {css: 'fa-ship', label: 'Ship'},
    {css: 'fa-shirtsinbulk', label: 'Shirtsinbulk'},
    {css: 'fa-shopping-cart', label: 'Shopping cart'},
    {css: 'fa-sign-in', label: 'Sign in'},
    {css: 'fa-sign-out', label: 'Sign out'},
    {css: 'fa-signal', label: 'Signal'},
    {css: 'fa-simplybuilt', label: 'Simplybuilt'},
    {css: 'fa-sitemap', label: 'Sitemap'},
    {css: 'fa-skyatlas', label: 'Skyatlas'},
    {css: 'fa-skype', label: 'Skype'},
    {css: 'fa-slack', label: 'Slack'},
    {css: 'fa-sliders', label: 'Sliders'},
    {css: 'fa-slideshare', label: 'Slideshare'},
    {css: 'fa-smile-o', label: 'Smile o'},
    {css: 'fa-sort', label: 'Sort'},
    {css: 'fa-sort-alpha-asc', label: 'Sort alpha asc'},
    {css: 'fa-sort-alpha-desc', label: 'Sort alpha desc'},
    {css: 'fa-sort-amount-asc', label: 'Sort amount asc'},
    {css: 'fa-sort-amount-desc', label: 'Sort amount desc'},
    {css: 'fa-sort-asc', label: 'Sort asc'},
    {css: 'fa-sort-desc', label: 'Sort desc'},
    {css: 'fa-sort-numeric-asc', label: 'Sort numeric asc'},
    {css: 'fa-sort-numeric-desc', label: 'Sort numeric desc'},
    {css: 'fa-soundcloud', label: 'Soundcloud'},
    {css: 'fa-space-shuttle', label: 'Space shuttle'},
    {css: 'fa-spinner', label: 'Spinner'},
    {css: 'fa-spoon', label: 'Spoon'},
    {css: 'fa-spotify', label: 'Spotify'},
    {css: 'fa-square', label: 'Square'},
    {css: 'fa-square-o', label: 'Square o'},
    {css: 'fa-stack-exchange', label: 'Stack exchange'},
    {css: 'fa-stack-overflow', label: 'Stack overflow'},
    {css: 'fa-star', label: 'Star'},
    {css: 'fa-star-half', label: 'Star half'},
    {css: 'fa-star-half-o', label: 'Star half o'},
    {css: 'fa-star-o', label: 'Star o'},
    {css: 'fa-steam', label: 'Steam'},
    {css: 'fa-steam-square', label: 'Steam square'},
    {css: 'fa-step-backward', label: 'Step backward'},
    {css: 'fa-step-forward', label: 'Step forward'},
    {css: 'fa-stethoscope', label: 'Stethoscope'},
    {css: 'fa-sticky-note', label: 'Sticky note'},
    {css: 'fa-sticky-note-o', label: 'Sticky note o'},
    {css: 'fa-stop', label: 'Stop'},
    {css: 'fa-street-view', label: 'Street view'},
    {css: 'fa-strikethrough', label: 'Strikethrough'},
    {css: 'fa-stumbleupon', label: 'Stumbleupon'},
    {css: 'fa-stumbleupon-circle', label: 'Stumbleupon circle'},
    {css: 'fa-subscript', label: 'Subscript'},
    {css: 'fa-subway', label: 'Subway'},
    {css: 'fa-suitcase', label: 'Suitcase'},
    {css: 'fa-sun-o', label: 'Sun o'},
    {css: 'fa-superscript', label: 'Superscript'},
    {css: 'fa-table', label: 'Table'},
    {css: 'fa-tablet', label: 'Tablet'},
    {css: 'fa-tachometer', label: 'Tachometer'},
    {css: 'fa-tag', label: 'Tag'},
    {css: 'fa-tags', label: 'Tags'},
    {css: 'fa-tasks', label: 'Tasks'},
    {css: 'fa-taxi', label: 'Taxi'},
    {css: 'fa-television', label: 'Television'},
    {css: 'fa-tencent-weibo', label: 'Tencent weibo'},
    {css: 'fa-terminal', label: 'Terminal'},
    {css: 'fa-text-height', label: 'Text height'},
    {css: 'fa-text-width', label: 'Text width'},
    {css: 'fa-th', label: 'Th'},
    {css: 'fa-th-large', label: 'Th large'},
    {css: 'fa-th-list', label: 'Th list'},
    {css: 'fa-thumb-tack', label: 'Thumb tack'},
    {css: 'fa-thumbs-down', label: 'Thumbs down'},
    {css: 'fa-thumbs-o-down', label: 'Thumbs o down'},
    {css: 'fa-thumbs-o-up', label: 'Thumbs o up'},
    {css: 'fa-thumbs-up', label: 'Thumbs up'},
    {css: 'fa-ticket', label: 'Ticket'},
    {css: 'fa-times', label: 'Times'},
    {css: 'fa-times-circle', label: 'Times circle'},
    {css: 'fa-times-circle-o', label: 'Times circle o'},
    {css: 'fa-tint', label: 'Tint'},
    {css: 'fa-toggle-off', label: 'Toggle off'},
    {css: 'fa-toggle-on', label: 'Toggle on'},
    {css: 'fa-trademark', label: 'Trademark'},
    {css: 'fa-train', label: 'Train'},
    {css: 'fa-transgender', label: 'Transgender'},
    {css: 'fa-transgender-alt', label: 'Transgender alt'},
    {css: 'fa-trash', label: 'Trash'},
    {css: 'fa-trash-o', label: 'Trash o'},
    {css: 'fa-tree', label: 'Tree'},
    {css: 'fa-trello', label: 'Trello'},
    {css: 'fa-tripadvisor', label: 'Tripadvisor'},
    {css: 'fa-trophy', label: 'Trophy'},
    {css: 'fa-truck', label: 'Truck'},
    {css: 'fa-try', label: 'Try'},
    {css: 'fa-tty', label: 'Tty'},
    {css: 'fa-tumblr', label: 'Tumblr'},
    {css: 'fa-tumblr-square', label: 'Tumblr square'},
    {css: 'fa-twitch', label: 'Twitch'},
    {css: 'fa-twitter', label: 'Twitter'},
    {css: 'fa-twitter-square', label: 'Twitter square'},
    {css: 'fa-umbrella', label: 'Umbrella'},
    {css: 'fa-underline', label: 'Underline'},
    {css: 'fa-undo', label: 'Undo'},
    {css: 'fa-university', label: 'University'},
    {css: 'fa-unlock', label: 'Unlock'},
    {css: 'fa-unlock-alt', label: 'Unlock alt'},
    {css: 'fa-upload', label: 'Upload'},
    {css: 'fa-usd', label: 'Usd'},
    {css: 'fa-user', label: 'User'},
    {css: 'fa-user-md', label: 'User md'},
    {css: 'fa-user-plus', label: 'User plus'},
    {css: 'fa-user-secret', label: 'User secret'},
    {css: 'fa-user-times', label: 'User times'},
    {css: 'fa-users', label: 'Users'},
    {css: 'fa-venus', label: 'Venus'},
    {css: 'fa-venus-double', label: 'Venus double'},
    {css: 'fa-venus-mars', label: 'Venus mars'},
    {css: 'fa-viacoin', label: 'Viacoin'},
    {css: 'fa-video-camera', label: 'Video camera'},
    {css: 'fa-vimeo', label: 'Vimeo'},
    {css: 'fa-vimeo-square', label: 'Vimeo square'},
    {css: 'fa-vine', label: 'Vine'},
    {css: 'fa-vk', label: 'Vk'},
    {css: 'fa-volume-down', label: 'Volume down'},
    {css: 'fa-volume-off', label: 'Volume off'},
    {css: 'fa-volume-up', label: 'Volume up'},
    {css: 'fa-weibo', label: 'Weibo'},
    {css: 'fa-weixin', label: 'Weixin'},
    {css: 'fa-whatsapp', label: 'Whatsapp'},
    {css: 'fa-wheelchair', label: 'Wheelchair'},
    {css: 'fa-wifi', label: 'Wifi'},
    {css: 'fa-wikipedia-w', label: 'Wikipedia w'},
    {css: 'fa-windows', label: 'Windows'},
    {css: 'fa-wordpress', label: 'Wordpress'},
    {css: 'fa-wrench', label: 'Wrench'},
    {css: 'fa-xing', label: 'Xing'},
    {css: 'fa-xing-square', label: 'Xing square'},
    {css: 'fa-y-combinator', label: 'Y combinator'},
    {css: 'fa-yahoo', label: 'Yahoo'},
    {css: 'fa-yelp', label: 'Yelp'},
    {css: 'fa-youtube', label: 'Youtube'},
    {css: 'fa-youtube-play', label: 'Youtube play'},
    {css: 'fa-youtube-square', label: 'Youtube square'}
  ];

  public getAllIconClasses(): Observable<Array<FontIcon>> {
    return of(this.fontIconClasses);
  }

}
